title = "SimpleDash"
theme = "dark"
loginRequired = false
allowProxy = ["https://www.metaweather.com/", "https://ifconfig.co/json"]

[session]
  name = "simpledash-session"

[users]
  [[users._public_.card]]
    type = "weather"
    title = "Weather"
    data = {"woeid" = "2442047"}

  [[users._public_.card]]
    type = "api"
    title = "Server IP (API card example)"
    url = "https://ifconfig.co/json"
    data = {"format" = """
    <p class="subtitle">${data.ip}</p>
    Country: ${data.country} (${data.country_iso})
    Time zone: ${data.time_zone}
    """}

  [users.admin]
    passwordHash = "$2a$10$w00dzQ1PP6nwXLhuzV2pFOUU6m8bcZXtDX3UVxpOYq3fTSwVMqPge"
    showPublic = true

    [[users.admin.card]]
      type = "status"
      title = "Google"
      icon = "ion:logo-google"
      desc = "Google search engine. Status card example."
      url = "https://www.google.com"

    [[users.admin.card]]
      type = "simple"
      title = "Gmail"
      icon = "simple-icons:gmail"
      desc = "Gmail mail client. Simple card example"
      url = "https://mail.google.com/"

    [[users.admin.card]]
      type = "collection"
      title = "Programming"
      icon = "entypo:code"
      [users.admin.card.data]
        Godoc = {"url" = "https://pkg.go.dev", "target" = "newTab"}
        Ruby-Doc = {"url" = "https://ruby-doc.org/", "target" = "sameTab"}

    [[users.admin.card]]
      type = "collection"
      title = "Science"
      icon = "ic:outline-science"
      data = {"Google Scholar" = {"url" = "https://scholar.google.com/", "target" = "sameTab"}}